### ISSUE TITLE
Non matching file name

### ISSUE THREAD

**Issue by AldeRoberge** [LucaBianco/UnityVoxelEngine#1]
![image](https://user-images.githubusercontent.com/4276275/222945004-e25b5063-6c47-4261-b9ac-4c363a1a7e83.png)

I was getting an error because the file and the class don't have the same name

Error : Broken prefabs with missing scripts

**Comment by LucaBianco** [comment]
I don't get any errors, not even a warning. But I believe you.
Did you fix it by just renaming the file?
I could also separate the class from the structure and enums.
Anyway, thanks for pointing this out.

**Comment by LucaBianco** [comment]
I think it's fixed now, I've separated the class and put it into its own file.
Please let me know if you encounter other issues
